### ISSUE TITLE
Boot fails

### ISSUE THREAD

**Issue by romangg** [r0b0/debian-installer#101]
After cc7849b installing a new system doesn't work for me. I'm running the installer script alone (with some changes to it in a feature branch, but these should be unrelated).

Install works fine but on reboot after entering my encryption key it says that initrd-switch-root.service failed and falls back to emergency mode.

**Comment by romangg** [comment]
Adding back the line `btrfs subvolume set-default ${top_level_mount}/@` to the install script makes it work for me again.

**Comment by r0b0** [comment]
Can you double check that you have 'subvol=@' in rootflags in your kernel command line?

This is ment to replace the default subvolume setting

**Comment by romangg** [comment]
After the boot fails in the emergency shell I issued `cat /proc/cmdline` which returns 
```initrd=\bf... rootfstype=btrfs rootflags=compress=zstd:1,subvol=@ rd.auto=1 ...```
So I suppose it's set.

**Comment by romangg** [comment]
Could the line just be added back or would this again make timeshift not work?

I tried to read up a bit on the rootflags and what is expected and what not in regards to subvolumes, but there is not a lot of documentation and it's not clear to me why `subvol=@` doesn't seem to work in my case.

I tested this now on real hardware and a QEMU virtual machine.

Maybe @thunderbird-93 from #88 can chime in what he knows about it. You don't need the `btrfs subvolume set-default ${top_level_mount}/@` line for boot to work?

**Comment by thunderbird-93** [comment]
@romangg, my understanding is that `btrfs subvolume set-default ${top_level_mount}/@` something timeshift needs. otherwise it fails to detect suitable btrfs partition. maybe it should be applied after the installation. I used previous version of the installer (June) and then had to issue `btrfs subvolume set-default` after reboot to make timeshift work. all I did described in [this post](https://github.com/r0b0/debian-installer/issues/88#issuecomment-2194652291).

**Comment by r0b0** [comment]
I suspect I know what the problem is. Support for the rootflags option was only added in systemd in December 2022 https://github.com/systemd/systemd/pull/25816/commits/57ec158cd81c11158b14fe98b51d08398cae99f3
With the systemd version in bookworm, it is ignored.

That's why it works when using my images (they use systemd from bookworm-backports) and for @thunderbird-93 (I think he mentioned that he uses trixie.)

@romangg can you try the installer.sh script from the "backports" branch please? https://github.com/r0b0/debian-installer/blob/backports/installer.sh It will enable bookworm-backports and take systemd (and much more) from there.

**Comment by romangg** [comment]
Amazing problem analysis! Indeed with the change pasted from the[ backports branch](https://github.com/r0b0/debian-installer/blob/backports/installer.sh), the system now unlocks.

**Comment by r0b0** [comment]
What's wrong with my server image?

**Comment by romangg** [comment]
Nothing in particular. But I can't directly verify its integrity without creating it myself via the scripts. Using the Debian live image has a shorter chain of trust so to speak.
